### ISSUE TITLE
typing text to find a tag not working correctly anymore

### ISSUE THREAD

**Issue by FredMark** [OpenLitterMap/openlittermap-web#205] opened 2021-03-23 11:18 UTC
if you choose a category, for instance 'Other', it is possible to scroll down the list, but because they are in random order and the list is long, it can be timeconsuming to find the right tag.
That is why we have the option to start typing the tag that you are looking for and those tags that do have the text that you typed so far, will be shown.

However, this is not working correctly anymore. If you have done it once, it doesn't seem to work and choosing another category also not working anymore. (if you do that, the tag appears in the other column, strange things happening).
Only option is to refresh the screen.
Investigate and solve.

**Comment by GeniJaho** [comment] 2021-07-15 16:28
@FredMark I can't reproduce this. They're working fine, even if you do it multiple times, and changing categories.

**Comment by biomassives** [comment] 2021-08-18 19:57
This dialogue crashed our app today on a Samsung Galaxy Android model SM-G930VL

**Comment by xlcrr** [comment] 2024-03-31 10:02
Thanks for the report @biomassives a lot of updates since then, just catching up on issues and PRs now. Going to close this until a new bug report comes along

**Closed by xlcrr** 2024-03-31 10:02 UTC
